import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
/* styles/globals.css */
import 'bootstrap/dist/css/bootstrap.min.css';



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Top Movie',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <div>
      <Navbar/>
      </div>
        {children}</body>
     
    </html>
  )
}
